### ISSUE TITLE
Ruby 1.9.1 support

### ISSUE THREAD

**Issue by pedz** [flori/json#76]
With Ruby 1.9.1 p378, an rvm gemset with just json_pure installed will fail on the expression (from irb):

    ruby-1.9.1-p378 :001 > JSON.generate({:foo => "bar"})
    NoMethodError: undefined method `generate' for #<JSON::Ext::Generator::State:0x000001010c2de8>
	from /usr/local/rvm/gems/ruby-1.9.1-p378@raptor/gems/json_pure-1.5.1/lib/json/common.rb:212:in `generate'
	from (irb):1
	from /usr/local/rvm/rubies/ruby-1.9.1-p378/bin/irb:16:in `<main>'

The same sequence works with Ruby 1.9.2
