### ISSUE TITLE
Fails to build on Ruby 2.0.0 since v2.5.0

### ISSUE THREAD

**Issue by piotrmurach** [flori/json#464]
Since release `2.5.0`, the `json` gem fails to compile its C extensions on the Ruby 2.0.0. In the gemspec, the supported version is `2.0.0` or higher. However, the tests on Travis only run against `2.3` hence why this has slipped through the net.

Here's the error:

```
linking shared-object json/ext/parser.so
parser.o: In function `JSON_parse_float':
C:\Ruby200\lib\ruby\gems\2.0.0\gems\json-2.5.1\ext\json\ext\parser/parser.rl:405:
undefined reference to `rb_funcallv'
collect2.exe: error: ld returned 1 exit status
make: *** [parser.so] Error 1
```

For a full log output please see [pastel CI output on Ruby 2.0.0](https://ci.appveyor.com/project/piotrmurach/pastel/build/job/y4xvm2tj615k1be3)

This is not a critical issue for me per se as I can pin the version down to something that works. However, I think it would be good to either fix the issue or release a version of `json` gem that works with Ruby `2.3` and higher.
